services:
  _defaults:
    public: true

  # Demo configuration text form
  prestashop.module.productblock.form.type.productblock_configuration_text:
    class: 'PrestaShop\Module\ProductBlock\Form\ProductblockConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.productblock.form.productblock_configuration_text_data_configuration:
    class: 'PrestaShop\Module\ProductBlock\Form\ProductblockConfigurationTextDataConfiguration'
    arguments: [ '@prestashop.adapter.legacy.configuration' ]

  prestashop.module.productblock.form.productblock_configuration_text_form_data_provider:
    class: 'PrestaShop\Module\ProductBlock\Form\ProductblockConfigurationTextFormDataProvider'
    arguments:
      - '@prestashop.module.productblock.form.productblock_configuration_text_data_configuration'

  prestashop.module.productblock.form.productblock_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.productblock.form.productblock_configuration_text_form_data_provider'
      - 'PrestaShop\Module\ProductBlock\Form\ProductblockConfigurationFormType'
      - 'ProductblockConfiguration'